In [1]:
import pandas as pd
df=pd.read_csv("Crop recommendation dataset.csv")
df

,CROPS,TYPE_OF_CROP,SOIL,SEASON,SOWN,HARVESTED,WATER_SOURCE,SOIL_PH,SOIL_PH_HIGH,CROPDURATION,...,WATERREQUIRED,WATERREQUIRED_MAX,RELATIVE_HUMIDITY,RELATIVE_HUMIDITY_MAX,N,N_MAX,P,P_MAX,K,K_MAX
0,rice,cereals,Alluvial soil,kharif,Jun,Sep,irrigated,7.6,8.0,116.9,...,2462.3,2500,73.8,80,82.4,100,40.7,60,42.2,60
1,rice,cereals,Loamy soil,kharif,Jul,Oct,rainfed,6.2,8.0,117.9,...,1237.5,2500,60.9,80,90.5,100,51.3,60,46.2,60
2,rice,cereals,Clay soil,kharif,Jun,Sep,irrigated,6.7,8.0,117.7,...,1075.1,2500,67.5,80,86.2,100,50.7,60,44.4,60
3,rice,cereals,Alluvial soil,kharif,Jul,Oct,rainfed,6.1,8.0,149.8,...,1549.9,2500,73.6,80,91.3,100,51.3,60,44.5,60
4,rice,cereals,Loamy soil,kharif,Jun,Sep,irrigated,8.0,8.0,131.7,...,1306.4,2500,60.3,80,81.3,100,48.6,60,51.0,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56995,small onion,bulbvegetables,sandy Loamy soil,Zaid,Mar,Mar,rainfed,6.2,7.0,86.6,...,701.9,750,66.0,75,73.8,100,44.5,60,57.9,60
56996,small onion,bulbvegetables,sandy Loamy soil,Zaid,Apr,Apr,irrigated,6.4,7.0,70.3,...,653.5,750,66.2,75,72.4,100,50.5,60,55.1,60
56997,small onion,bulbvegetables,sandy Loamy soil,Zaid,May,May,rainfed,6.4,7.0,86.3,...,743.3,750,65.6,75,70.5,100,59.8,60,58.5,60
56998,small onion,bulbvegetables,sandy Loamy soil,Zaid,Jun,Jun,irrigated,6.2,7.0,89.1,...,736.8,750,74.2,75,66.8,100,40.2,60,55.3,60
56999,small onion,bulbvegetables,sandy Loamy soil,Zaid,Jul,Jul,rainfed,6.7,7.0,90.0,...,726.0,750,72.1,75,65.2,100,52.0,60,58.6,60

In [2]:
df.isnull()

,CROPS,TYPE_OF_CROP,SOIL,SEASON,SOWN,HARVESTED,WATER_SOURCE,SOIL_PH,SOIL_PH_HIGH,CROPDURATION,...,WATERREQUIRED,WATERREQUIRED_MAX,RELATIVE_HUMIDITY,RELATIVE_HUMIDITY_MAX,N,N_MAX,P,P_MAX,K,K_MAX
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [3]:
df.columns

Index(['CROPS', 'TYPE_OF_CROP', 'SOIL', 'SEASON', 'SOWN', 'HARVESTED',
       'WATER_SOURCE', 'SOIL_PH', 'SOIL_PH_HIGH', 'CROPDURATION',
       'CROPDURATION_MAX', 'TEMP', 'MAX_TEMP', 'WATERREQUIRED',
       'WATERREQUIRED_MAX', 'RELATIVE_HUMIDITY', 'RELATIVE_HUMIDITY_MAX', 'N',
       'N_MAX', 'P', 'P_MAX', 'K', 'K_MAX'],
      dtype='str')

In [4]:
df.drop(["TYPE_OF_CROP"],axis=1)
df["N-Ratio"]=df["N"]/df["N_MAX"]
df["P-Ratio"]=df["P"]/df["P_MAX"]
df["K-Ratio"]=df["K"]/df["K_MAX"]

In [5]:
df

,CROPS,TYPE_OF_CROP,SOIL,SEASON,SOWN,HARVESTED,WATER_SOURCE,SOIL_PH,SOIL_PH_HIGH,CROPDURATION,...,RELATIVE_HUMIDITY_MAX,N,N_MAX,P,P_MAX,K,K_MAX,N-Ratio,P-Ratio,K-Ratio
0,rice,cereals,Alluvial soil,kharif,Jun,Sep,irrigated,7.6,8.0,116.9,...,80,82.4,100,40.7,60,42.2,60,0.824,0.678333,0.703333
1,rice,cereals,Loamy soil,kharif,Jul,Oct,rainfed,6.2,8.0,117.9,...,80,90.5,100,51.3,60,46.2,60,0.905,0.855000,0.770000
2,rice,cereals,Clay soil,kharif,Jun,Sep,irrigated,6.7,8.0,117.7,...,80,86.2,100,50.7,60,44.4,60,0.862,0.845000,0.740000
3,rice,cereals,Alluvial soil,kharif,Jul,Oct,rainfed,6.1,8.0,149.8,...,80,91.3,100,51.3,60,44.5,60,0.913,0.855000,0.741667
4,rice,cereals,Loamy soil,kharif,Jun,Sep,irrigated,8.0,8.0,131.7,...,80,81.3,100,48.6,60,51.0,60,0.813,0.810000,0.850000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56995,small onion,bulbvegetables,sandy Loamy soil,Zaid,Mar,Mar,rainfed,6.2,7.0,86.6,...,75,73.8,100,44.5,60,57.9,60,0.738,0.741667,0.965000
56996,small onion,bulbvegetables,sandy Loamy soil,Zaid,Apr,Apr,irrigated,6.4,7.0,70.3,...,75,72.4,100,50.5,60,55.1,60,0.724,0.841667,0.918333
56997,small onion,bulbvegetables,sandy Loamy soil,Zaid,May,May,rainfed,6.4,7.0,86.3,...,75,70.5,100,59.8,60,58.5,60,0.705,0.996667,0.975000
56998,small onion,bulbvegetables,sandy Loamy soil,Zaid,Jun,Jun,irrigated,6.2,7.0,89.1,...,75,66.8,100,40.2,60,55.3,60,0.668,0.670000,0.921667
56999,small onion,bulbvegetables,sandy Loamy soil,Zaid,Jul,Jul,rainfed,6.7,7.0,90.0,...,75,65.2,100,52.0,60,58.6,60,0.652,0.866667,0.976667

In [6]:
df.columns

Index(['CROPS', 'TYPE_OF_CROP', 'SOIL', 'SEASON', 'SOWN', 'HARVESTED',
       'WATER_SOURCE', 'SOIL_PH', 'SOIL_PH_HIGH', 'CROPDURATION',
       'CROPDURATION_MAX', 'TEMP', 'MAX_TEMP', 'WATERREQUIRED',
       'WATERREQUIRED_MAX', 'RELATIVE_HUMIDITY', 'RELATIVE_HUMIDITY_MAX', 'N',
       'N_MAX', 'P', 'P_MAX', 'K', 'K_MAX', 'N-Ratio', 'P-Ratio', 'K-Ratio'],
      dtype='str')

In [7]:
X=df[["SOIL","SEASON","SOWN","WATER_SOURCE","SOIL_PH","SOIL_PH_HIGH",'TEMP', 'MAX_TEMP', 'RELATIVE_HUMIDITY', 'RELATIVE_HUMIDITY_MAX', 'N','N_MAX', 'P', 'P_MAX', 'K', 'K_MAX', 'N-Ratio', 'P-Ratio', 'K-Ratio',
    ]]

y=df[["CROPS","WATERREQUIRED","HARVESTED","CROPDURATION"]]

In [8]:
y

             CROPS  WATERREQUIRED HARVESTED  CROPDURATION
0             rice         2462.3       Sep         116.9
1             rice         1237.5       Oct         117.9
2             rice         1075.1       Sep         117.7
3             rice         1549.9       Oct         149.8
4             rice         1306.4       Sep         131.7
...            ...            ...       ...           ...
56995  small onion          701.9       Mar          86.6
56996  small onion          653.5       Apr          70.3
56997  small onion          743.3       May          86.3
56998  small onion          736.8       Jun          89.1
56999  small onion          726.0       Jul          90.0

[57000 rows x 4 columns]

In [9]:
X.columns

Index(['SOIL', 'SEASON', 'SOWN', 'WATER_SOURCE', 'SOIL_PH', 'SOIL_PH_HIGH',
       'TEMP', 'MAX_TEMP', 'RELATIVE_HUMIDITY', 'RELATIVE_HUMIDITY_MAX', 'N',
       'N_MAX', 'P', 'P_MAX', 'K', 'K_MAX', 'N-Ratio', 'P-Ratio', 'K-Ratio'],
      dtype='str')

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,          
    random_state=42,    
    shuffle=True  
)

In [11]:
df["CROPS"].nunique()

57

In [12]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 45600 entries, 22035 to 56422
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SOIL                   45600 non-null  str
 1   SEASON                 45600 non-null  str
 2   SOWN                   45600 non-null  str
 3   WATER_SOURCE           45600 non-null  str
 4   SOIL_PH                45600 non-null  float64
 5   SOIL_PH_HIGH           45600 non-null  float64
 6   TEMP                   45600 non-null  float64
 7   MAX_TEMP               45600 non-null  int64
 8   RELATIVE_HUMIDITY      45600 non-null  float64
 9   RELATIVE_HUMIDITY_MAX  45600 non-null  int64
 10  N                      45600 non-null  float64
 11  N_MAX                  45600 non-null  int64
 12  P                      45600 non-null  float64
 13  P_MAX                  45600 non-null  int64
 14  K                      45600 non-null  float64
 15  K_MAX                  45600 non-null  int64
 16  N-Ratio                45600 non-null  float64
 17  P-Ratio                45600 non-null  float64
 18  K-Ratio                45600 non-null  float64
dtypes: float64(10), int64(5), str(4)
memory usage: 7.0 MB

In [13]:
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder


def prepare_y(y_dataframe, string_col_name):
    str_col = y_dataframe[string_col_name]
    num_cols = y_dataframe.drop(columns=[string_col_name]).values
    le = LabelEncoder()
    labels_int = le.fit_transform(str_col)
    labels_onehot = tf.keras.utils.to_categorical(labels_int)
    y_final = np.hstack([labels_onehot, num_cols])
    
    return y_final, le
y_train_ready, le_model = prepare_y(y_train, 'CROPS')
y_test_ready, _ = prepare_y(y_test, 'CROPS')

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

categorical_cols = ['SOIL', 'SEASON', 'SOWN', 'WATER_SOURCE']

numerical_cols = [
    'SOIL_PH', 'SOIL_PH_HIGH', 'TEMP', 'MAX_TEMP', 
    'RELATIVE_HUMIDITY', 'RELATIVE_HUMIDITY_MAX', 
    'N', 'N_MAX', 'P', 'P_MAX', 'K', 'K_MAX', 
    'N-Ratio', 'P-Ratio', 'K-Ratio'
]

y_train_crop = y_train_ready[:, :57]
y_test_crop = y_test_ready[:, :57]


preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_cols)
    ])

X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

In [15]:
y_train_ready

array([[0.0, 0.0, 0.0, ..., 1125.0, 'Oct', 139.3],
       [1.0, 0.0, 0.0, ..., 433.3, 'Jul', 147.1],
       [0.0, 0.0, 0.0, ..., 1000.0, 'Apr', 292.5],
       ...,
       [0.0, 0.0, 0.0, ..., 1592.7, 'Sep', 127.8],
       [0.0, 0.0, 0.0, ..., 800.0, 'Apr', 104.8],
       [0.0, 0.0, 0.0, ..., 741.7, 'May', 81.5]],
      shape=(45600, 60), dtype=object)

In [16]:
dim = X_train_encoded.shape[1]

In [17]:
from tensorflow.keras import layers, models

inputA = layers.Input(shape=(dim,), name="Main_Input")
x = layers.Dense(128, activation="relu")(inputA)
x = layers.Dense(64, activation="relu")(x)
x = layers.Dense(32, activation="relu")(x)
output_crop = layers.Dense(57, activation="softmax", name="crop_output")(x)
output_nums = layers.Dense(3, activation="linear", name="metrics_output")(x)

model = models.Model(inputs=inputA, outputs=[output_crop, output_nums])

In [18]:

model.compile(
    optimizer='adam',
    loss={
        'crop_output': 'categorical_crossentropy', 
        'metrics_output': 'mse'
    },
    metrics={'crop_output': 'accuracy', 'metrics_output': 'mae'}
)

In [19]:

month_map = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}

y_train_cleaned = y_train.copy()
y_test_cleaned = y_test.copy()

for col in y_train_cleaned.columns:
    if y_train_cleaned[col].dtype == 'object' and col != 'CROPS':
        y_train_cleaned[col] = y_train_cleaned[col].map(month_map)
        y_test_cleaned[col] = y_test_cleaned[col].map(month_map)

y_train_nums = y_train_cleaned.drop(columns=['CROPS']).values
y_test_nums = y_test_cleaned.drop(columns=['CROPS']).values

In [20]:
import numpy as np

month_map = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}


y_train_num_df = y_train.drop(columns=['CROPS']).copy()
y_test_num_df = y_test.drop(columns=['CROPS']).copy()

y_train_num_df['HARVESTED'] = y_train_num_df['HARVESTED'].map(month_map)
y_test_num_df['HARVESTED'] = y_test_num_df['HARVESTED'].map(month_map)

y_train_nums = y_train_num_df.values.astype('float32')
y_test_nums = y_test_num_df.values.astype('float32')

In [21]:
X_train_final = np.asarray(X_train_encoded).astype('float32')
X_test_final = np.asarray(X_test_encoded).astype('float32')


train_targets = {
    'crop_output': y_train_crop.astype('float32'),
    'metrics_output': np.asarray(y_train_nums).astype('float32')
}

test_targets = {
    'crop_output': y_test_crop.astype('float32'),
    'metrics_output': np.asarray(y_test_nums).astype('float32')
}

history = model.fit(
    X_train_final, 
    train_targets,
    validation_data=(X_test_final, test_targets),
    epochs=40,
    batch_size=32
)

Epoch 1/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - crop_output_accuracy: 0.0240 - crop_output_loss: 4.8579 - loss: 40530.5898 - metrics_output_loss: 40525.7344 - metrics_output_mae: 93.3864 - val_crop_output_accuracy: 0.0321 - val_crop_output_loss: 4.6045 - val_loss: 15601.6299 - val_metrics_output_loss: 15585.5068 - val_metrics_output_mae: 65.0050
Epoch 2/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.0422 - crop_output_loss: 4.7978 - loss: 11201.0098 - metrics_output_loss: 11196.2080 - metrics_output_mae: 54.7533 - val_crop_output_accuracy: 0.0408 - val_crop_output_loss: 4.3931 - val_loss: 7734.1665 - val_metrics_output_loss: 7720.7402 - val_metrics_output_mae: 46.6021
Epoch 3/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.1214 - crop_output_loss: 3.5019 - loss: 6677.1108 - metrics_output_loss: 6673.6035 - metrics_output_mae: 42.6327 - val_crop_output_accuracy: 0.1677 - val_crop_output_loss: 2.8320 - val_loss: 5979.9883 - val_metrics_output_loss: 5969.8564 - val_metrics_output_mae: 40.0965
Epoch 4/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.2197 - crop_output_loss: 2.6133 - loss: 5713.5498 - metrics_output_loss: 5710.9365 - metrics_output_mae: 38.4796 - val_crop_output_accuracy: 0.2299 - val_crop_output_loss: 2.5529 - val_loss: 5662.7388 - val_metrics_output_loss: 5656.3594 - val_metrics_output_mae: 37.6616
Epoch 5/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.2904 - crop_output_loss: 2.2779 - loss: 5363.1313 - metrics_output_loss: 5360.8496 - metrics_output_mae: 35.7289 - val_crop_output_accuracy: 0.3543 - val_crop_output_loss: 2.1694 - val_loss: 5298.9629 - val_metrics_output_loss: 5294.3428 - val_metrics_output_mae: 34.7863
Epoch 6/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.3673 - crop_output_loss: 1.9802 - loss: 5218.8140 - metrics_output_loss: 5216.8350 - metrics_output_mae: 33.8876 - val_crop_output_accuracy: 0.3286 - val_crop_output_loss: 1.9133 - val_loss: 5178.6606 - val_metrics_output_loss: 5170.6675 - val_metrics_output_mae: 33.0820
Epoch 7/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.4314 - crop_output_loss: 1.7631 - loss: 5088.2500 - metrics_output_loss: 5086.4834 - metrics_output_mae: 32.5254 - val_crop_output_accuracy: 0.3927 - val_crop_output_loss: 1.6874 - val_loss: 5378.0020 - val_metrics_output_loss: 5371.7061 - val_metrics_output_mae: 33.2228
Epoch 8/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.4786 - crop_output_loss: 1.6071 - loss: 5031.2383 - metrics_output_loss: 5029.6343 - metrics_output_mae: 31.8758 - val_crop_output_accuracy: 0.4321 - val_crop_output_loss: 1.7840 - val_loss: 5320.4932 - val_metrics_output_loss: 5315.6333 - val_metrics_output_mae: 32.7484
Epoch 9/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.5243 - crop_output_loss: 1.4622 - loss: 4992.0679 - metrics_output_loss: 4990.6055 - metrics_output_mae: 31.1953 - val_crop_output_accuracy: 0.5445 - val_crop_output_loss: 1.4646 - val_loss: 5244.5049 - val_metrics_output_loss: 5242.1260 - val_metrics_output_mae: 32.2468
Epoch 10/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.5597 - crop_output_loss: 1.3355 - loss: 4963.1807 - metrics_output_loss: 4961.8496 - metrics_output_mae: 30.7965 - val_crop_output_accuracy: 0.5920 - val_crop_output_loss: 1.2855 - val_loss: 5043.9663 - val_metrics_output_loss: 5042.5239 - val_metrics_output_mae: 30.9330
Epoch 11/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.5966 - crop_output_loss: 1.2414 - loss: 4910.1499 - metrics_output_loss: 4908.9043 - metrics_output_mae: 30.2442 - val_crop_output_accuracy: 0.6076 - val_crop_output_loss: 1.2124 - val_loss: 4954.3115 - val_metrics_output_loss: 4951.9116 - val_metrics_output_mae: 30.1387
Epoch 12/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.6310 - crop_output_loss: 1.1347 - loss: 4922.4561 - metrics_output_loss: 4921.3237 - metrics_output_mae: 30.0751 - val_crop_output_accuracy: 0.6355 - val_crop_output_loss: 1.1065 - val_loss: 5171.6841 - val_metrics_output_loss: 5167.8257 - val_metrics_output_mae: 31.3158
Epoch 13/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.6626 - crop_output_loss: 1.0561 - loss: 4917.6426 - metrics_output_loss: 4916.5874 - metrics_output_mae: 29.8180 - val_crop_output_accuracy: 0.6285 - val_crop_output_loss: 1.0606 - val_loss: 4913.3301 - val_metrics_output_loss: 4909.1924 - val_metrics_output_mae: 29.4863
Epoch 14/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.6937 - crop_output_loss: 0.9830 - loss: 4888.4395 - metrics_output_loss: 4887.4497 - metrics_output_mae: 29.6060 - val_crop_output_accuracy: 0.7124 - val_crop_output_loss: 0.9158 - val_loss: 5284.1382 - val_metrics_output_loss: 5278.3892 - val_metrics_output_mae: 30.9932
Epoch 15/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - crop_output_accuracy: 0.7174 - crop_output_loss: 0.9015 - loss: 4905.3125 - metrics_output_loss: 4904.4136 - metrics_output_mae: 29.4918 - val_crop_output_accuracy: 0.7498 - val_crop_output_loss: 0.7791 - val_loss: 4895.6680 - val_metrics_output_loss: 4893.1411 - val_metrics_output_mae: 29.2664
Epoch 16/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - crop_output_accuracy: 0.7400 - crop_output_loss: 0.8344 - loss: 4882.3647 - metrics_output_loss: 4881.5308 - metrics_output_mae: 29.3022 - val_crop_output_accuracy: 0.7230 - val_crop_output_loss: 0.8425 - val_loss: 4939.7148 - val_metrics_output_loss: 4937.6938 - val_metrics_output_mae: 29.3483
Epoch 17/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.7641 - crop_output_loss: 0.7683 - loss: 4844.0088 - metrics_output_loss: 4843.2412 - metrics_output_mae: 29.1368 - val_crop_output_accuracy: 0.8104 - val_crop_output_loss: 0.6182 - val_loss: 4946.0854 - val_metrics_output_loss: 4940.8276 - val_metrics_output_mae: 29.0895
Epoch 18/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.7903 - crop_output_loss: 0.7021 - loss: 4858.3599 - metrics_output_loss: 4857.6621 - metrics_output_mae: 29.0916 - val_crop_output_accuracy: 0.8314 - val_crop_output_loss: 0.6141 - val_loss: 4999.3667 - val_metrics_output_loss: 4995.7109 - val_metrics_output_mae: 29.7464
Epoch 19/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.7993 - crop_output_loss: 0.6629 - loss: 4861.9478 - metrics_output_loss: 4861.2798 - metrics_output_mae: 29.0779 - val_crop_output_accuracy: 0.7743 - val_crop_output_loss: 0.6306 - val_loss: 4920.8374 - val_metrics_output_loss: 4917.8301 - val_metrics_output_mae: 29.0931
Epoch 20/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.8190 - crop_output_loss: 0.6121 - loss: 4845.4463 - metrics_output_loss: 4844.8311 - metrics_output_mae: 28.9502 - val_crop_output_accuracy: 0.7983 - val_crop_output_loss: 0.6094 - val_loss: 5062.8833 - val_metrics_output_loss: 5059.4468 - val_metrics_output_mae: 29.4396
Epoch 21/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.8307 - crop_output_loss: 0.5780 - loss: 4851.6938 - metrics_output_loss: 4851.1128 - metrics_output_mae: 28.8855 - val_crop_output_accuracy: 0.7788 - val_crop_output_loss: 0.5813 - val_loss: 5042.6152 - val_metrics_output_loss: 5035.2319 - val_metrics_output_mae: 29.6571
Epoch 22/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.8463 - crop_output_loss: 0.5269 - loss: 4845.0752 - metrics_output_loss: 4844.5503 - metrics_output_mae: 28.8758 - val_crop_output_accuracy: 0.8739 - val_crop_output_loss: 0.4799 - val_loss: 4908.5625 - val_metrics_output_loss: 4903.6016 - val_metrics_output_mae: 28.8899
Epoch 23/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.8557 - crop_output_loss: 0.4921 - loss: 4810.5723 - metrics_output_loss: 4810.0825 - metrics_output_mae: 28.6825 - val_crop_output_accuracy: 0.8563 - val_crop_output_loss: 0.4720 - val_loss: 4973.8599 - val_metrics_output_loss: 4970.5605 - val_metrics_output_mae: 29.3381
Epoch 24/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.8648 - crop_output_loss: 0.4668 - loss: 4824.8618 - metrics_output_loss: 4824.3989 - metrics_output_mae: 28.7126 - val_crop_output_accuracy: 0.8731 - val_crop_output_loss: 0.4445 - val_loss: 4841.6328 - val_metrics_output_loss: 4837.5000 - val_metrics_output_mae: 28.6101
Epoch 25/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.8666 - crop_output_loss: 0.4538 - loss: 4831.2842 - metrics_output_loss: 4830.8340 - metrics_output_mae: 28.7388 - val_crop_output_accuracy: 0.9087 - val_crop_output_loss: 0.3549 - val_loss: 4840.7153 - val_metrics_output_loss: 4837.5737 - val_metrics_output_mae: 28.5286
Epoch 26/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.8814 - crop_output_loss: 0.4111 - loss: 4835.3730 - metrics_output_loss: 4834.9595 - metrics_output_mae: 28.6845 - val_crop_output_accuracy: 0.8898 - val_crop_output_loss: 0.3459 - val_loss: 4946.3267 - val_metrics_output_loss: 4940.2642 - val_metrics_output_mae: 28.9199
Epoch 27/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.8894 - crop_output_loss: 0.3933 - loss: 4822.4272 - metrics_output_loss: 4822.0396 - metrics_output_mae: 28.6246 - val_crop_output_accuracy: 0.8546 - val_crop_output_loss: 0.4405 - val_loss: 4986.9766 - val_metrics_output_loss: 4984.6709 - val_metrics_output_mae: 29.3269
Epoch 28/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.8974 - crop_output_loss: 0.3625 - loss: 4804.0210 - metrics_output_loss: 4803.6538 - metrics_output_mae: 28.5893 - val_crop_output_accuracy: 0.8961 - val_crop_output_loss: 0.3148 - val_loss: 4929.0806 - val_metrics_output_loss: 4925.5977 - val_metrics_output_mae: 28.9875
Epoch 29/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.9003 - crop_output_loss: 0.3441 - loss: 4817.9478 - metrics_output_loss: 4817.6040 - metrics_output_mae: 28.6512 - val_crop_output_accuracy: 0.9305 - val_crop_output_loss: 0.2637 - val_loss: 5162.8784 - val_metrics_output_loss: 5163.5327 - val_metrics_output_mae: 30.2090
Epoch 30/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.9111 - crop_output_loss: 0.3183 - loss: 4798.4028 - metrics_output_loss: 4798.0806 - metrics_output_mae: 28.6146 - val_crop_output_accuracy: 0.9383 - val_crop_output_loss: 0.3074 - val_loss: 4831.0518 - val_metrics_output_loss: 4826.4312 - val_metrics_output_mae: 28.3353
Epoch 31/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.9127 - crop_output_loss: 0.3104 - loss: 4821.6816 - metrics_output_loss: 4821.3657 - metrics_output_mae: 28.5836 - val_crop_output_accuracy: 0.8847 - val_crop_output_loss: 0.3622 - val_loss: 4859.8823 - val_metrics_output_loss: 4856.1904 - val_metrics_output_mae: 28.6442
Epoch 32/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.9201 - crop_output_loss: 0.2898 - loss: 4801.8013 - metrics_output_loss: 4801.5112 - metrics_output_mae: 28.5100 - val_crop_output_accuracy: 0.9555 - val_crop_output_loss: 0.2202 - val_loss: 4913.5391 - val_metrics_output_loss: 4908.5791 - val_metrics_output_mae: 28.7362
Epoch 33/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.9210 - crop_output_loss: 0.2854 - loss: 4783.8467 - metrics_output_loss: 4783.5518 - metrics_output_mae: 28.4615 - val_crop_output_accuracy: 0.9425 - val_crop_output_loss: 0.2546 - val_loss: 5145.2563 - val_metrics_output_loss: 5147.9297 - val_metrics_output_mae: 30.1619
Epoch 34/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - crop_output_accuracy: 0.9231 - crop_output_loss: 0.2797 - loss: 4801.3535 - metrics_output_loss: 4801.0645 - metrics_output_mae: 28.5624 - val_crop_output_accuracy: 0.9216 - val_crop_output_loss: 0.2543 - val_loss: 5560.6104 - val_metrics_output_loss: 5562.1328 - val_metrics_output_mae: 31.4860
Epoch 35/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - crop_output_accuracy: 0.9321 - crop_output_loss: 0.2504 - loss: 4788.1030 - metrics_output_loss: 4787.8535 - metrics_output_mae: 28.4850 - val_crop_output_accuracy: 0.9703 - val_crop_output_loss: 0.1627 - val_loss: 4961.4688 - val_metrics_output_loss: 4956.5229 - val_metrics_output_mae: 28.6836
Epoch 36/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - crop_output_accuracy: 0.9305 - crop_output_loss: 0.2553 - loss: 4813.9272 - metrics_output_loss: 4813.6729 - metrics_output_mae: 28.5418 - val_crop_output_accuracy: 0.9369 - val_crop_output_loss: 0.1940 - val_loss: 4917.4238 - val_metrics_output_loss: 4915.2866 - val_metrics_output_mae: 28.7219
Epoch 37/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.9389 - crop_output_loss: 0.2293 - loss: 4774.5386 - metrics_output_loss: 4774.3096 - metrics_output_mae: 28.3597 - val_crop_output_accuracy: 0.9489 - val_crop_output_loss: 0.1880 - val_loss: 4816.8647 - val_metrics_output_loss: 4811.6123 - val_metrics_output_mae: 28.5241
Epoch 38/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.9416 - crop_output_loss: 0.2201 - loss: 4787.3271 - metrics_output_loss: 4787.1016 - metrics_output_mae: 28.4983 - val_crop_output_accuracy: 0.9393 - val_crop_output_loss: 0.2004 - val_loss: 5086.8325 - val_metrics_output_loss: 5085.5132 - val_metrics_output_mae: 29.6763
Epoch 39/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.9438 - crop_output_loss: 0.2138 - loss: 4774.1626 - metrics_output_loss: 4773.9502 - metrics_output_mae: 28.3232 - val_crop_output_accuracy: 0.9617 - val_crop_output_loss: 0.1423 - val_loss: 5060.9048 - val_metrics_output_loss: 5059.7998 - val_metrics_output_mae: 29.6070
Epoch 40/40
1425/1425 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - crop_output_accuracy: 0.9417 - crop_output_loss: 0.2224 - loss: 4776.9688 - metrics_output_loss: 4776.7466 - metrics_output_mae: 28.4015 - val_crop_output_accuracy: 0.9686 - val_crop_output_loss: 0.1540 - val_loss: 5149.0146 - val_metrics_output_loss: 5151.1528 - val_metrics_output_mae: 29.9434

In [22]:
model.save("take2.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [23]:
import joblib

joblib.dump(preprocessor, 'preprocessor.pkl')

joblib.dump(le_model, 'label_encoder.pkl')

print("Artifacts saved: preprocessor.pkl and label_encoder.pkl")

Artifacts saved: preprocessor.pkl and label_encoder.pkl

In [24]:
model = tf.keras.models.load_model("take2.h5")

ValueError: Could not deserialize 'keras.metrics.mse' because it is not a KerasSaveable subclass